# .pre-commit-config.yaml

repos:
  # Black for Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3.9  # Replace with your Python version

  # Flake8 for linting Python code
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest stable version
    hooks:
      - id: flake8
        args: ['--max-line-length=120']

  # MyPy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.0  # Use the latest stable version
    hooks:
      - id: mypy

  # End-of-file fixer to ensure newline at the end of files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer

  # Check for trailing whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace

  # YAML file format check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
