[project]
name = "scouting-calendar-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl==3.1.5",
    "streamlit==1.58.0",
    "plotly==6.8.0",
    "unidecode==1.4.0",
    "geopandas==1.1.3",
    "xlrd==2.0.2",
    "gdown==6.1.0",
]

[dependency-groups]
dev = [
    "pre-commit==4.6.0",
    "ruff==0.15.16",
    "ty==0.0.44",
]

[tool.ty.environment]
# Aggiungi la cartella app come source root
root = ["app"]
