[client]
# toolbarMode = "minimal"
showSidebarNavigation = false

[ui]
hideTopBar = true

[server]
runOnSave = true

#[theme]
# base = "light"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#FFFFFF"
# textColor = "#000000"
